### ISSUE TITLE
Add lattice layout plot

### ISSUE THREAD

**Issue by coldfix** [hibtc/madgui#10]
@DavidSagan, you were interested in this kind of plot right? Do you have any starting point for me?

**Comment by DavidSagan** [comment]
Actually since the madqt plotting of orbits, etc., already displays  layout information I don't think we need a separate lattice layout plot.

Right now it looks like each element is displayed using a different color. More useful would be to assign a different color (and height) to element groups. See "12.10.8 Defining Shapes for Lat_layout and Floor_plan Drawings" in the Tao manual.
