### ISSUE TITLE
Rework quantity display / edit controls

### ISSUE THREAD

**Issue by coldfix** [hibtc/madgui#3]
@DavidSagan reported:

> *) Left justify real and integer values.
> *) Add a third column for the units. I am planning to modify the Tao "python" command to return the units of various parameters.
> *) Get rid of the up/down increment arrows for reals and integers since they are of only very limited usefulness.
> *) Modify the displayed real numbers to give full accuracy.

**Comment by coldfix** [comment]
> *) Left justify real and integer values.
> *) Add a third column for the units. I am planning to modify the Tao "python" command to return the units of various parameters.

Personally, I think right-justified numbers look much cleaner. ;) And I prefer a single control that can deal with both unit + number at the same time. On the other hand, I agree that the current set of controls is too much complexity for little gain, so maybe you're right here. If you think you can simplify things, I will be okay with it.

> *) Get rid of the up/down increment arrows for reals and integers since they are of only very limited usefulness.

Why get rid of them when we get them almost for free from the Qt widget?

> *) Modify the displayed real numbers to give full accuracy.

IMO, full accuracy is usually visual overkill and distracting for normal use. On the other hand, I agree that it should be possible to access the full value. How about adding a config option that sets how many digits will be displayed? So far, I thought it's enough to let the user export the values to .yml files.

**Comment by DavidSagan** [comment]
1) Left/Right justification: If there were only numbers then right justification would make sense. However mixing left and right justification looks wrong to me (see first screen shot) and slows down my scanning of the data. All Left justification is a standard (see https://ux.stackexchange.com/questions/24066/what-is-the-best-practice-for-data-table-cell-content-alignment). All right justification is another possibility. I still like all left but all right is still much better than mixed.

![screen shot 2017-06-01 at 9 09 42 pm](https://cloud.githubusercontent.com/assets/1026006/26706986/971c9d56-470f-11e7-9bc2-98ee5789ae3c.png)

![screen shot 2017-06-01 at 9 16 10 pm](https://cloud.githubusercontent.com/assets/1026006/26706993/9f4f2a52-470f-11e7-93ae-24bd98d7a55b.png)

2) Extra column for units: Thinking about it now I would say that if we go with all left justification then having unit + number in one column makes sense. With all right justification I am thinking that having a separate column would make things look better (more aligned). But this is not a big deal for me.

3) up/down increment arrows: I would get rid of them since they add visual clutter and I don't think they will be useful. One thing we could do is temporarily remove them and if they are missed then they could be restored.

4) Accuracy of displayed numbers: OK I agree full accuracy is a bit of overkill (I was a bit too hasty in writing this). But deciding how many digits to display is a bit problematical. The problem is that you need different accuracies for different parameters and how many digits a user will want change depending upon the problem. For example, if you are comparing two similar orbits you might want to see  9 digits or more. I like the idea of being able to change the number of displayed digits and I think that the user should be able to vary this while the madqt is running. One thing that could be useful is a "madqt settings" window where such things as the displayed accuracy can be set. (Also toggle if up/down arrows are displayed, etc.)

**Comment by coldfix** [comment]
1. Okay, you convinced me: all-left it is. [done, see 4f893b0621048750a3f33bbdc1e3590b9f677eaa]

2. Okay. If we left-adjust, we should either keep the unit in the same control or add a column with the unit on the left side.

3. Okay.

4. Let's start with something like this until we have a better idea: config option for default number format + can be modified using some kind of preference dialog +(?) when going into input mode, the full accuracy is displayed always.

**Comment by DavidSagan** [comment]
2. I have modified my thinking here and could go either way. I'll leave the final decision to you.

4. Sounds like a good plan.

**Comment by coldfix** [comment]
FYI:
1. After having tried it, I still prefer right-aligned numbers. So, I have added a config option that defaults to left-align, so you don't have to deal with config files for now.
2. Okay, then I will leave it as it is for now.
3. I will add a config option for this tonight.
4. same as 3

**Comment by coldfix** [comment]
I have implemented the following changes:

By default, no wheels are shown.

The number format can be configured in the config file and can also be set from the main menu. At some point it will probably be nice to have a more convenient "toggle" like option to immediately show full precision with just 1 click, but I will leave this for the future.
